---
core:
 num_workers: 100

inventory:
 plugin: nornir.plugins.inventory.simple.SimpleInventory
 options:
  host_file: "geomap/inventory/hosts.yaml"
  group_file: "geomap/inventory/groups.yaml"
  defaults_file: "geomap/inventory/defaults.yaml"