# Generated by Django 2.1.2 on 2019-02-13 11:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reachability_tool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equiment',
            name='countdown',
            field=models.IntegerField(default=42),
        ),
        migrations.AlterField(
            model_name='equiment',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 2, 13, 11, 31, 32, 216915, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='equiment',
            name='ip',
            field=models.GenericIPAddressField(unique=True, verbose_name='IP'),
        ),
    ]
