# Generated by Django 2.1.2 on 2019-02-13 11:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reachability_tool', '0002_auto_20190213_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('1', 'OK'), ('0', 'Alert')], max_length=1)),
                ('ip', models.GenericIPAddressField(unique=True, verbose_name='IP')),
                ('date', models.DateField(default=datetime.datetime(2019, 2, 13, 11, 35, 57, 472325, tzinfo=utc))),
                ('countdown', models.IntegerField(default=42)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='equiment',
            name='user',
        ),
        migrations.DeleteModel(
            name='Equiment',
        ),
    ]
