# Generated by Django 2.1.2 on 2019-02-13 12:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reachability_tool', '0003_auto_20190213_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 13, 12, 42, 33, 375847, tzinfo=utc)),
        ),
    ]
