# Generated by Django 2.1.2 on 2019-03-11 03:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reachability_tool', '0004_auto_20190213_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 11, 3, 20, 18, 77632, tzinfo=utc)),
        ),
    ]
