# Generated by Django 2.0.13 on 2019-03-12 00:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reachability_tool', '0007_auto_20190312_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 12, 0, 23, 34, 267866, tzinfo=utc)),
        ),
    ]
