# Generated by Django 2.0.13 on 2019-03-13 22:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reachability_tool', '0009_auto_20190312_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 13, 22, 58, 53, 106622, tzinfo=utc)),
        ),
    ]
