# Generated by Django 2.0.13 on 2019-03-14 00:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reachability_tool', '0010_auto_20190313_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='countdown',
        ),
        migrations.RemoveField(
            model_name='device',
            name='date',
        ),
        migrations.AddField(
            model_name='device',
            name='target',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 25, 0, 2, 53, 909281, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='device',
            name='ticket',
            field=models.CharField(default='NETENG-6940', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='state',
            field=models.CharField(choices=[('2', 'Fail'), ('1', 'OK'), ('0', 'Alert')], max_length=1),
        ),
    ]
