# Generated by Django 2.0.13 on 2019-03-14 00:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reachability_tool', '0011_auto_20190314_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='user',
        ),
        migrations.AlterField(
            model_name='device',
            name='target',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 25, 0, 7, 20, 125091, tzinfo=utc)),
        ),
    ]
