# Generated by Django 2.0.13 on 2019-03-15 15:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reachability_tool', '0012_auto_20190314_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='reporter',
            field=models.CharField(default='nimam', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='target',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 26, 15, 49, 32, 674877, tzinfo=utc)),
        ),
    ]
