# Generated by Django 2.0.13 on 2019-03-15 16:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reachability_tool', '0013_auto_20190315_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='target',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 26, 16, 24, 33, 255336, tzinfo=utc)),
        ),
    ]
