# Generated by Django 2.1.2 on 2019-03-23 00:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reachability_tool', '0014_auto_20190315_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='target',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 4, 0, 29, 20, 80337, tzinfo=utc)),
        ),
    ]
