# Generated by Django 2.1.2 on 2019-04-02 03:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reachability_tool', '0015_auto_20190323_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='target',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 14, 3, 16, 32, 181407, tzinfo=utc)),
        ),
    ]
