# Generated by Django 2.1.2 on 2019-04-02 03:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reachability_tool', '0016_auto_20190402_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='target',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 14, 3, 24, 14, 913696, tzinfo=utc)),
        ),
    ]
