# Generated by Django 2.1.2 on 2019-04-26 03:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reachability_tool', '0018_auto_20190426_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='target',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 7, 3, 14, 36, 880562, tzinfo=utc)),
        ),
    ]
