# Generated by Django 2.1.2 on 2019-05-07 01:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reachability_tool', '0019_auto_20190426_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='target',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 18, 1, 40, 3, 300370, tzinfo=utc)),
        ),
    ]
