# Generated by Django 2.1.2 on 2019-05-08 01:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reachability_tool', '0020_auto_20190507_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='target',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 19, 1, 38, 34, 261866, tzinfo=utc)),
        ),
    ]
