# Generated by Django 2.1.2 on 2019-05-09 00:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reachability_tool', '0022_auto_20190509_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='target',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 20, 0, 22, 48, 653454, tzinfo=utc)),
        ),
    ]
