# Generated by Django 2.1.2 on 2018-11-21 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geomap', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='status',
        ),
    ]
