# Generated by Django 2.1.2 on 2018-10-15 02:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import geomap.helper_functions


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geomap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=geomap.helper_functions.user_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slack_id', models.CharField(blank=True, max_length=120, null=True)),
                ('position', models.CharField(blank=True, max_length=120, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=120)),
                ('loopback', models.GenericIPAddressField()),
                ('node', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name_plural': 'Properties'},
        ),
        migrations.AddField(
            model_name='property',
            name='business_unit',
            field=models.CharField(blank=True, choices=[('FH', 'Fision Home'), ('FP', 'Fision Plus'), ('FS', 'Fision Stay'), ('FE', 'Fision Encore'), ('FW', 'Fision Work'), ('FU', 'Fision U'), ('Demo', 'Demo')], max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='cross_connect',
            field=models.DateField(blank=True, null=True, verbose_name='Cross-Connected'),
        ),
        migrations.AddField(
            model_name='property',
            name='gear_installed',
            field=models.DateField(blank=True, null=True, verbose_name='Installed'),
        ),
        migrations.AddField(
            model_name='property',
            name='gear_ready',
            field=models.DateField(blank=True, null=True, verbose_name='Ready For Pickup'),
        ),
        migrations.AddField(
            model_name='property',
            name='hld',
            field=models.FileField(blank=True, null=True, upload_to=geomap.helper_functions.user_directory_path),
        ),
        migrations.AddField(
            model_name='property',
            name='mr_cert',
            field=models.DateField(blank=True, null=True, verbose_name='MR Cert'),
        ),
        migrations.AddField(
            model_name='property',
            name='osp_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='participants',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='property',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True, unique=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='property',
            name='type',
            field=models.CharField(blank=True, choices=[('NC', 'New Coonstruction'), ('LC', 'Conversion/OverBuild')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='units',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='router',
            name='feeding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeder', to='geomap.Property'),
        ),
        migrations.AddField(
            model_name='router',
            name='routering',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='router', to='geomap.Property'),
        ),
        migrations.AddField(
            model_name='file',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='geomap.Property'),
        ),
    ]
