# Generated by Django 2.1.2 on 2018-10-18 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geomap', '0002_auto_20181015_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='fiber_ready',
            field=models.DateField(blank=True, null=True, verbose_name='Fiber Ready'),
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(blank=True, choices=[('NC', 'New Construction'), ('LC', 'Conversion/OverBuild')], max_length=50, null=True),
        ),
    ]
