# Generated by Django 2.1.2 on 2018-11-21 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geomap', '0002_remove_property_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='channel_id',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
