# Generated by Django 2.1.2 on 2018-10-18 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geomap', '0003_auto_20181018_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
