# Generated by Django 2.1.2 on 2018-12-09 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geomap', '0004_property_market'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='channel_id',
            field=models.CharField(max_length=120, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='gear_installed',
            field=models.DateField(blank=True, null=True, verbose_name='Gear Installed'),
        ),
        migrations.AlterField(
            model_name='property',
            name='gpon_ready',
            field=models.DateField(blank=True, null=True, verbose_name='Chassis Ready'),
        ),
        migrations.AlterField(
            model_name='property',
            name='market',
            field=models.CharField(blank=True, choices=[('SEFL', 'SEFL'), ('SWFL', 'SWFL'), ('ATL', 'ATL'), ('NC/SC', 'NC/SC'), ('CFL', 'CFL')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='network_ready',
            field=models.DateField(blank=True, null=True, verbose_name='Router Ready'),
        ),
    ]
