# Generated by Django 2.1.2 on 2019-05-21 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geomap', '0004_auto_20190519_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='prop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geomap.Property'),
        ),
        migrations.AddField(
            model_name='property',
            name='gpon_ont',
            field=models.IntegerField(blank=True, null=True, verbose_name='ONT'),
        ),
        migrations.AlterField(
            model_name='property',
            name='gpon_cards',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cards'),
        ),
        migrations.AlterField(
            model_name='property',
            name='gpon_chassis',
            field=models.IntegerField(blank=True, null=True, verbose_name='# Chassis'),
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(blank=True, choices=[('New Construction', 'New Construction'), ('Conversion/OverBuild', 'Conversion/OverBuild'), ('Update', 'Update')], max_length=50, null=True),
        ),
    ]
