# Generated by Django 2.1.2 on 2018-10-26 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geomap', '0004_property_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='router',
            name='feeding',
        ),
        migrations.RemoveField(
            model_name='router',
            name='routering',
        ),
        migrations.AddField(
            model_name='property',
            name='feeds',
            field=models.ManyToManyField(blank=True, null=True, to='geomap.Property'),
        ),
    ]
