# Generated by Django 2.1.2 on 2018-10-27 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geomap', '0005_auto_20181026_0144'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Router',
            new_name='Equiment',
        ),
        migrations.RemoveField(
            model_name='property',
            name='cross_connect',
        ),
        migrations.RemoveField(
            model_name='property',
            name='participants',
        ),
        migrations.AddField(
            model_name='property',
            name='Cross-Connected',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='cpm',
            field=models.ForeignKey(limit_choices_to=models.Q(groups__name='CPM'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cpm', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='property',
            name='cxceng',
            field=models.ForeignKey(limit_choices_to=models.Q(groups__name='CXCENG'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cxceng', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='property',
            name='fe',
            field=models.ForeignKey(limit_choices_to=models.Q(groups__name='FE'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fe', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='property',
            name='gponeng',
            field=models.ForeignKey(limit_choices_to=models.Q(groups__name='GPONENG'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gponeng', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='property',
            name='neteng',
            field=models.ForeignKey(limit_choices_to=models.Q(groups__name='NETENG'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='neteng', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='property',
            name='pm',
            field=models.ForeignKey(limit_choices_to=models.Q(groups__name='PM'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pm', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='property',
            name='business_unit',
            field=models.CharField(blank=True, choices=[('Fision Home', 'Fision Home'), ('Fision Plus', 'Fision Plus'), ('Fision Stay', 'Fision Stay'), ('Fision Encore', 'Fision Encore'), ('Fision Work', 'Fision Work'), ('Fision U', 'Fision U'), ('Demo', 'Demo')], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='feeds',
            field=models.ManyToManyField(to='geomap.Property'),
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(blank=True, choices=[('New Construction', 'New Construction'), ('Conversion/OverBuild', 'Conversion/OverBuild')], max_length=50, null=True),
        ),
    ]
