# Generated by Django 2.1.2 on 2019-05-21 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geomap', '0005_auto_20190521_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='mgn',
            field=models.GenericIPAddressField(unique=True),
        ),
    ]
