# Generated by Django 2.1.2 on 2018-12-10 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geomap', '0005_auto_20181209_1729'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='Files',
        ),
    ]
