# Generated by Django 2.1.2 on 2018-10-27 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geomap', '0006_auto_20181027_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='Cross-Connected',
        ),
        migrations.AddField(
            model_name='property',
            name='cross_connect',
            field=models.DateField(blank=True, null=True, verbose_name='Cross-Connected'),
        ),
    ]
