# Generated by Django 2.1.2 on 2019-05-21 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geomap', '0006_auto_20190521_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='prop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geomap.Property'),
        ),
    ]
