# Generated by Django 2.1.2 on 2019-01-18 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geomap', '0006_auto_20181210_0355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='osp_id',
        ),
        migrations.AddField(
            model_name='property',
            name='netbox_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
