# Generated by Django 2.1.2 on 2019-05-21 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geomap', '0007_auto_20190521_0120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='r_loop',
        ),
        migrations.RemoveField(
            model_name='property',
            name='router',
        ),
        migrations.RemoveField(
            model_name='property',
            name='s_loop',
        ),
        migrations.RemoveField(
            model_name='property',
            name='switch',
        ),
        migrations.AddField(
            model_name='property',
            name='mgn_ip',
            field=models.GenericIPAddressField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='interface',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='geomap.Device'),
        ),
    ]
