# Generated by Django 2.1.2 on 2019-01-19 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geomap', '0007_auto_20190118_0244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='router',
        ),
        migrations.AddField(
            model_name='property',
            name='equipment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
