# Generated by Django 2.1.2 on 2019-05-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geomap', '0008_auto_20190521_0233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='mgn_ip',
            new_name='r_mgn',
        ),
        migrations.AddField(
            model_name='property',
            name='network',
            field=models.CharField(blank=True, choices=[('MediaRoom', 'MediaRoom'), ('ProIdiom', 'ProIdiom'), ('ClearIP', 'ClearIP')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='nomadix_lan',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='IP MGN'),
        ),
        migrations.AddField(
            model_name='property',
            name='nomadix_wan',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='IP MGN'),
        ),
        migrations.AddField(
            model_name='property',
            name='router',
            field=models.CharField(blank=True, choices=[('7600', '7600'), ('ASR9006', 'ASR9006')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='s_mgn',
            field=models.GenericIPAddressField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='property',
            name='security',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='IP MGN'),
        ),
        migrations.AddField(
            model_name='property',
            name='switch',
            field=models.CharField(blank=True, choices=[('2960', '2960'), ('ASR920', 'ASR920')], max_length=50, null=True),
        ),
    ]
