# Generated by Django 2.1.2 on 2019-01-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geomap', '0008_auto_20190119_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='s_loop',
        ),
        migrations.RemoveField(
            model_name='property',
            name='switch',
        ),
        migrations.AlterField(
            model_name='property',
            name='equipment',
            field=models.CharField(blank=True, choices=[('7600', '7600'), ('ASR9006', 'ASR9006')], max_length=200, null=True),
        ),
    ]
