# Generated by Django 2.1.2 on 2018-10-28 23:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geomap', '0008_auto_20181027_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='gpon_feed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gpon_feeds', to='geomap.Property', verbose_name='Fed from'),
        ),
        migrations.AlterField(
            model_name='property',
            name='cpm',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(groups__name='CPM'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cpm', to=settings.AUTH_USER_MODEL, verbose_name='CPM'),
        ),
        migrations.AlterField(
            model_name='property',
            name='cxceng',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(groups__name='CXCENG'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cxceng', to=settings.AUTH_USER_MODEL, verbose_name='CXC Engineer'),
        ),
        migrations.AlterField(
            model_name='property',
            name='fe',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(groups__name='FE'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fe', to=settings.AUTH_USER_MODEL, verbose_name='Field Engineer'),
        ),
        migrations.AlterField(
            model_name='property',
            name='feeds',
            field=models.ManyToManyField(to='geomap.Property', verbose_name='Router Fed from'),
        ),
        migrations.AlterField(
            model_name='property',
            name='gponeng',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(groups__name='GPONENG'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gponeng', to=settings.AUTH_USER_MODEL, verbose_name='GPON Engineer'),
        ),
        migrations.AlterField(
            model_name='property',
            name='neteng',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(groups__name='NETENG'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='neteng', to=settings.AUTH_USER_MODEL, verbose_name='Network Engineer'),
        ),
        migrations.AlterField(
            model_name='property',
            name='pm',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(groups__name='PM'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pm', to=settings.AUTH_USER_MODEL, verbose_name='PM'),
        ),
    ]
