# Generated by Django 2.1.2 on 2019-05-24 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geomap', '0009_auto_20190524_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='contract',
            field=models.CharField(blank=True, choices=[('Not Applicable', 'Not Applicable'), ('In Sales Phase', 'In Sales Phase'), ('Pendnig', 'Pendnig'), ('Received', 'Received'), ('LOST', 'LOST'), ('NOT Approved to Upgrade', 'NOT Approved to Upgrade')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='ip_data_bulk',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='IP DATA BULK'),
        ),
        migrations.AddField(
            model_name='property',
            name='services',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='gpon_ont',
            field=models.CharField(blank=True, choices=[('G0240G-A', 'G0240G-A'), ('G0241G-A', 'G0241G-A')], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='router',
            field=models.CharField(blank=True, choices=[('7600', '7600'), ('ASR9K', 'ASR9K')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='switch',
            field=models.CharField(blank=True, choices=[('N9K-C93180YC-EX', 'N9K-C93180YC-EX'), ('WS-C2960X-24PS-L', 'WS-C2960X-24PS-L'), ('WS-C3750G-24PS', 'WS-C3750G-24PS'), ('ME-3400-24TS-A', 'ME-3400-24TS-A'), ('ME-3400G-12CS-A', 'ME-3400G-12CS-A'), ('ASR-920-12CZ-A', 'ASR-920-12CZ-A'), ('SF302-08', 'SF302-08'), ('SG300-10PP', 'SG300-10PP')], max_length=50, null=True),
        ),
    ]
