# Generated by Django 2.1.2 on 2019-01-19 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geomap', '0009_auto_20190119_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='gpon_chassis',
            field=models.CharField(blank=True, choices=[('7600', '7600'), ('ASR9006', 'ASR9006')], max_length=200, null=True),
        ),
    ]
