# Generated by Django 2.1.2 on 2018-10-31 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geomap', '0009_auto_20181028_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='coa',
            field=models.BooleanField(default=False, verbose_name='COA'),
        ),
        migrations.AddField(
            model_name='property',
            name='rf_coa',
            field=models.BooleanField(default=False, verbose_name='RF COA'),
        ),
        migrations.AddField(
            model_name='property',
            name='rf_unit',
            field=models.BooleanField(default=False, verbose_name='RF In-Unit'),
        ),
        migrations.AlterField(
            model_name='property',
            name='feeds',
            field=models.ManyToManyField(related_name='feeding', to='geomap.Property', verbose_name='Fed from'),
        ),
        migrations.AlterField(
            model_name='property',
            name='gpon_feed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gpon_feeds', to='geomap.Property', verbose_name='GPON from'),
        ),
    ]
