# Generated by Django 2.1.2 on 2019-05-25 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geomap', '0010_auto_20190524_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('maxin', models.FloatField()),
                ('maxout', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='interface',
            name='status',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='interface',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interfaces', to='geomap.Device'),
        ),
        migrations.AlterField(
            model_name='property',
            name='nomadix_lan',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nomadix LAN'),
        ),
        migrations.AlterField(
            model_name='property',
            name='nomadix_wan',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nomadix WAN'),
        ),
        migrations.AlterField(
            model_name='property',
            name='security',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='statistics',
            name='interface',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geomap.Interface'),
        ),
    ]
