# Generated by Django 2.1.2 on 2018-11-01 02:49

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('geomap', '0010_auto_20181031_0229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='gear_ready',
        ),
        migrations.AddField(
            model_name='property',
            name='gpon_ready',
            field=models.DateField(blank=True, null=True, verbose_name='Ready For Pickup'),
        ),
        migrations.AddField(
            model_name='property',
            name='mdf_ready',
            field=models.DateField(blank=True, null=True, verbose_name='MDF Ready'),
        ),
        migrations.AddField(
            model_name='property',
            name='network_ready',
            field=models.DateField(blank=True, null=True, verbose_name='Ready For Pickup'),
        ),
        migrations.AddField(
            model_name='property',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, 'Created'), (1, 'Published'), (2, 'Ready for Installs'), (3, 'Ready for CXC'), (4, 'Ready for MR'), (5, 'Completed')], default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='stb_installed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='sub_id_ready',
            field=models.DateField(blank=True, null=True),
        ),
    ]
