# Generated by Django 2.1.2 on 2019-01-19 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geomap', '0010_auto_20190119_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='ont',
            field=models.CharField(blank=True, choices=[('7600', '7600'), ('ASR9006', 'ASR9006')], max_length=200, null=True),
        ),
    ]
