# Generated by Django 2.1.2 on 2019-05-26 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geomap', '0011_auto_20190525_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='node_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
