# Generated by Django 2.1.2 on 2019-01-22 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geomap', '0011_property_ont'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='equipment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='gpon_chassis',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='market',
            field=models.CharField(choices=[('SEFL', 'SEFL'), ('SWFL', 'SWFL'), ('ATL', 'ATL'), ('NC/SC', 'NC/SC'), ('CFL', 'CFL')], max_length=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='ont',
            field=models.CharField(blank=True, choices=[('G-240G-A', 'G-240G-A'), ('G-241G-A', 'G-241G-A')], max_length=200, null=True),
        ),
    ]
