# Generated by Django 2.1.2 on 2018-11-02 02:37

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('geomap', '0011_auto_20181101_0249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='published',
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, 'Created'), (1, 'Published'), (2, 'Ready for Installs'), (3, 'Ready for CXC'), (4, 'Ready for MR'), (5, 'Completed')], default=0, protected=True),
        ),
    ]
