# Generated by Django 2.1.2 on 2018-11-02 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geomap', '0012_auto_20181102_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='published',
            field=models.DateField(blank=True, null=True, verbose_name='Published On'),
        ),
    ]
