# Generated by Django 2.1.2 on 2019-01-28 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geomap', '0012_auto_20190122_0259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='ip_tv_coa',
            new_name='_iptvcoa',
        ),
    ]
