# Generated by Django 2.1.2 on 2019-02-06 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geomap', '0013_auto_20190128_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='card',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='rsp',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='RSP'),
        ),
    ]
