# Generated by Django 2.1.2 on 2018-11-03 13:54

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geomap', '0013_property_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='ip_data',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='IP DATA'),
        ),
        migrations.AddField(
            model_name='property',
            name='ip_mgn',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='IP MGN'),
        ),
        migrations.AddField(
            model_name='property',
            name='ip_mgn_ap',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='IP MGN WAP'),
        ),
        migrations.AddField(
            model_name='property',
            name='ip_tv',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='IP TV'),
        ),
        migrations.AddField(
            model_name='property',
            name='ip_tv_coa',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='IP TV COA'),
        ),
        migrations.AddField(
            model_name='property',
            name='ip_voice',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='IP VOICE'),
        ),
        migrations.AlterField(
            model_name='property',
            name='feeds',
            field=models.ManyToManyField(blank=True, related_name='feeding', to='geomap.Property', verbose_name='Fed from'),
        ),
        migrations.AlterField(
            model_name='property',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, srid=4326),
        ),
    ]
