# Generated by Django 2.1.2 on 2019-06-03 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geomap', '0013_auto_20190531_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interface',
            name='status',
        ),
    ]
