# Generated by Django 2.1.2 on 2018-11-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geomap', '0014_auto_20181103_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='router',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='ip_mgn_ap',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='IP MGN AP'),
        ),
    ]
