# Generated by Django 2.2.2 on 2019-06-05 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geomap', '0014_remove_interface_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='description',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='interface',
            name='status',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
