# Generated by Django 2.2.2 on 2019-06-18 13:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geomap', '0015_auto_20190605_0302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='image',
            new_name='file',
        ),
        migrations.RemoveField(
            model_name='property',
            name='cpm',
        ),
        migrations.RemoveField(
            model_name='property',
            name='cxceng',
        ),
        migrations.RemoveField(
            model_name='property',
            name='fe',
        ),
        migrations.RemoveField(
            model_name='property',
            name='gponeng',
        ),
        migrations.RemoveField(
            model_name='property',
            name='hld',
        ),
        migrations.RemoveField(
            model_name='property',
            name='neteng',
        ),
        migrations.RemoveField(
            model_name='property',
            name='pm',
        ),
        migrations.AddField(
            model_name='property',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='off_net',
            field=models.BooleanField(default=False, verbose_name='Offnet'),
        ),
        migrations.AddField(
            model_name='property',
            name='participants',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='property',
            name='contract',
            field=models.CharField(blank=True, choices=[('Not Applicable', 'Not Applicable'), ('In Sales Phase', 'In Sales Phase'), ('Pending', 'Pending'), ('Received', 'Received'), ('LOST', 'LOST'), ('NOT Approved to Upgrade', 'NOT Approved to Upgrade')], max_length=50, null=True),
        ),
    ]
