# Generated by Django 2.1.2 on 2019-03-11 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geomap', '0015_auto_20190311_0320'),
    ]

    operations = [
        migrations.AddField(
            model_name='equiment',
            name='prop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geomap.Property'),
        ),
    ]
