# Generated by Django 2.1.2 on 2018-11-03 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geomap', '0016_auto_20181103_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='router',
            field=models.CharField(blank=True, choices=[('7600', '7600'), ('ASR9006', 'ASR9006')], max_length=200, null=True),
        ),
    ]
