# Generated by Django 2.0.13 on 2019-03-12 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geomap', '0016_equiment_prop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equiment',
            name='prop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geomap.Property', verbose_name='Property'),
        ),
    ]
