# Generated by Django 2.2.2 on 2019-06-18 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geomap', '0017_property_markets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='markets',
            new_name='market',
        ),
    ]
