# Generated by Django 2.1.2 on 2018-11-04 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geomap', '0018_property_r_loop'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='s_loop',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Switch LB'),
        ),
        migrations.AlterField(
            model_name='property',
            name='r_loop',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='LB'),
        ),
    ]
