# Generated by Django 2.1.2 on 2019-04-02 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geomap', '0018_auto_20190323_0029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(blank=True, max_length=200, null=True)),
                ('os', models.CharField(choices=[('cisco_ios', 'Cisco IOS'), ('cisco_xr', 'Cisco XR'), ('nxos', 'Cisco NXOS')], max_length=120, null=True)),
                ('type', models.CharField(choices=[('router', 'Router'), ('switch', 'Switch'), ('chassis', 'Chassis'), ('ONT', 'ONT')], max_length=120, null=True)),
                ('topology', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='geomap.Topology')),
            ],
        ),
        migrations.RemoveField(
            model_name='device',
            name='topology',
        ),
        migrations.AddField(
            model_name='device',
            name='os',
            field=models.CharField(choices=[('cisco_ios', 'Cisco IOS'), ('cisco_xr', 'Cisco XR'), ('nxos', 'Cisco NXOS')], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='prop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='geomap.Property', verbose_name='Property'),
        ),
    ]
