# Generated by Django 2.1.2 on 2019-04-02 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geomap', '0019_auto_20190402_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='loopback',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
