# Generated by Django 2.1.2 on 2018-11-04 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geomap', '0019_auto_20181104_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='switch',
            field=models.CharField(blank=True, choices=[('2960', '2960'), ('ASR920', 'ASR920')], max_length=200, null=True),
        ),
    ]
