# Generated by Django 2.1.2 on 2019-04-26 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geomap', '0020_auto_20190402_0324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='card',
        ),
        migrations.RemoveField(
            model_name='property',
            name='rsp',
        ),
        migrations.RemoveField(
            model_name='property',
            name='topology',
        ),
    ]
