# Generated by Django 2.1.2 on 2018-11-06 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geomap', '0020_property_switch'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='done',
            field=models.DateField(blank=True, null=True, verbose_name='Completed'),
        ),
    ]
