# Generated by Django 2.1.2 on 2019-04-26 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geomap', '0021_auto_20190426_0217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='configured',
        ),
        migrations.RemoveField(
            model_name='device',
            name='installed',
        ),
        migrations.RemoveField(
            model_name='device',
            name='loopback',
        ),
        migrations.RemoveField(
            model_name='device',
            name='os',
        ),
        migrations.RemoveField(
            model_name='device',
            name='type',
        ),
        migrations.AddField(
            model_name='device',
            name='hostname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='mgn',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Management'),
        ),
        migrations.AddField(
            model_name='device',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='geomap.Device'),
        ),
    ]
