# Generated by Django 2.1.2 on 2019-05-08 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geomap', '0023_auto_20190507_0140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='equipment',
        ),
        migrations.AddField(
            model_name='property',
            name='main_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geomap.Device'),
        ),
    ]
