# Generated by Django 2.1.2 on 2019-05-09 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geomap', '0024_auto_20190508_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='router',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='interface',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='geomap.Device'),
        ),
    ]
