# Generated by Django 2.1.2 on 2019-05-09 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geomap', '0025_auto_20190509_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='prop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='geomap.Property', verbose_name='Property'),
        ),
    ]
